name: CMake Build (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release
  BUILD_DIR: "${{github.workspace}}/build"
  DIST_DIR: "${{github.workspace}}/build/dist"
jobs:
  x86_64:
    runs-on: windows-latest
    continue-on-error: ${{ !matrix.release }}
    strategy:
      matrix:
        include:
          - repo: https://github.com/JesseTG/melonDS.git
            commit: 6bcbd4e
            release: true
          - repo: https://github.com/melonDS-emu/melonDS.git
            commit: master
            release: false
            # This profile is used to receive advanced notice of breaking changes
    env:
      ARCHIVE_NAME: "melondsds_libretro-win32-x86_64"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

      - name: Install dependencies
        run: pacman -Sq --noconfirm git pkgconf mingw-w64-x86_64-{cmake,toolchain}
      - name: Create build environment
        run: mkdir --verbose --parents "$BUILD_DIR"
      - name: Configure
        working-directory: "${{ env.BUILD_DIR }}"
        run: cmake "$GITHUB_WORKSPACE" -G"MinGW Makefiles" -DMELONDS_REPOSITORY_URL:STRING="${{ matrix.repo }}" -DMELONDS_REPOSITORY_TAG:STRING="${{ matrix.commit }}"
      - name: Install GCC problem matcher
        uses: olemorud/gcc-problem-matcher@v1.0
      - name: Build
        working-directory: "${{ env.BUILD_DIR }}"
        run: mingw32-make -j$(nproc --all)
      - name: Prepare Artifact Directory
        if: matrix.release
        env:
          CORES_PATH: "${{ env.DIST_DIR }}/cores"
          INFO_PATH: "${{ env.DIST_DIR }}/info"
        run: |
          mkdir --parents "$CORES_PATH" "$INFO_PATH"
          cp --force "$BUILD_DIR/src/libretro/melondsds_libretro.dll" "$CORES_PATH"
          cp --force "$BUILD_DIR/melondsds_libretro.info" "$INFO_PATH"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: matrix.release
        with:
          name: ${{ env.ARCHIVE_NAME }}
          if-no-files-found: error
          path: "${{ env.DIST_DIR }}"